---
- name: hermes daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
  become: true
  become_user: "{{ username }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ hermes_user_uid.stdout }}"

- name: restart hermes-gateway
  ansible.builtin.systemd:
    name: hermes-gateway.service
    state: restarted
    scope: user
  become: true
  become_user: "{{ username }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ hermes_user_uid.stdout }}"

- name: restart hermes-proxy
  ansible.builtin.systemd:
    name: hermes-proxy.service
    state: restarted
    scope: user
  become: true
  become_user: "{{ username }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ hermes_user_uid.stdout }}"

- name: restart hermes-dashboard
  ansible.builtin.systemd:
    name: hermes-dashboard.service
    state: restarted
    scope: user
  become: true
  become_user: "{{ username }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ hermes_user_uid.stdout }}"
