---
- name: searxng daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
    scope: user
  become: true
  become_user: "{{ username }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ searxng_user_uid.stdout }}"

- name: restart searxng
  ansible.builtin.systemd:
    name: searxng.service
    state: restarted
    scope: user
  become: true
  become_user: "{{ username }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ searxng_user_uid.stdout }}"
  when: not ansible_check_mode
